<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8P2VZCD\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8P2VZCD/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/Container8P2VZCD.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\Container8P2VZCD\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \Container8P2VZCD\srcApp_KernelProdContainer([
    'container.build_hash' => '8P2VZCD',
    'container.build_id' => 'ca93588f',
    'container.build_time' => 1562744598,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8P2VZCD');
