<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mgVf8fa' shared service.

return $this->privates['.service_locator.mgVf8fa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'template' => ['privates', '.errored..service_locator.mgVf8fa.App\\Entity\\InvoiceTemplate', NULL, 'Cannot autowire service ".service_locator.mgVf8fa": it references class "App\\Entity\\InvoiceTemplate" but no such service exists.'],
]);
