<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._DaGI_7' shared service.

return $this->privates['.service_locator._DaGI_7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService.php', true],
]);
