<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.wOhakyu' shared service.

return $this->privates['.service_locator.wOhakyu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['privates', 'App\\Security\\RolePermissionManager', 'getRolePermissionManagerService.php', true],
]);
