<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.mRslStB' shared service.

return $this->privates['.service_locator.mRslStB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'entry' => ['privates', '.errored..service_locator.mRslStB.App\\Entity\\Timesheet', NULL, 'Cannot autowire service ".service_locator.mRslStB": it references class "App\\Entity\\Timesheet" but no such service exists.'],
]);
