<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tYuJIxe' shared service.

return $this->privates['.service_locator.tYuJIxe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'activityRepository' => ['privates', 'App\\Repository\\ActivityRepository', 'getActivityRepositoryService.php', true],
    'projectRepository' => ['privates', 'App\\Repository\\ProjectRepository', 'getProjectRepositoryService.php', true],
]);
