<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.lUi4zPv' shared service.

return $this->privates['.service_locator.lUi4zPv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'profile' => ['privates', '.errored..service_locator.lUi4zPv.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.lUi4zPv": it references class "App\\Entity\\User" but no such service exists.'],
    'repository' => ['privates', 'App\\Repository\\TimesheetRepository', 'getTimesheetRepositoryService', false],
]);
