<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8SSwaBs' shared service.

return $this->privates['.service_locator.8SSwaBs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'project' => ['privates', '.errored..service_locator.8SSwaBs.App\\Entity\\Project', NULL, 'Cannot autowire service ".service_locator.8SSwaBs": it references class "App\\Entity\\Project" but no such service exists.'],
]);
