<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.GMpqZBo' shared service.

return $this->privates['.service_locator.GMpqZBo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repository' => ['privates', 'App\\Repository\\TimesheetRepository', 'getTimesheetRepositoryService', false],
    'userToDelete' => ['privates', '.errored..service_locator.GMpqZBo.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.GMpqZBo": it references class "App\\Entity\\User" but no such service exists.'],
]);
