<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.neOJndj' shared service.

return $this->privates['.service_locator.neOJndj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'profile' => ['privates', '.errored..service_locator.neOJndj.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.neOJndj": it references class "App\\Entity\\User" but no such service exists.'],
]);
