<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\AclDecisionManager' shared autowired service.

include_once $this->targetDirs[3].'/src/Security/AclDecisionManager.php';

return $this->privates['App\\Security\\AclDecisionManager'] = new \App\Security\AclDecisionManager(($this->privates['security.access.decision_manager'] ?? $this->getSecurity_Access_DecisionManagerService()));
