<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\API\ActivityApiEditForm' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/EntityFormTrait.php';
include_once $this->targetDirs[3].'/src/Form/ActivityEditForm.php';
include_once $this->targetDirs[3].'/src/Form/API/ActivityApiEditForm.php';

return $this->privates['App\\Form\\API\\ActivityApiEditForm'] = new \App\Form\API\ActivityApiEditForm();
