<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\CreateReleaseCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/CreateReleaseCommand.php';

return $this->services['console.command.public_alias.App\\Command\\CreateReleaseCommand'] = new \App\Command\CreateReleaseCommand($this->targetDirs[3]);
