<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\ConfigurationController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/API/BaseApiController.php';
include_once $this->targetDirs[3].'/src/API/ConfigurationController.php';

$this->services['App\\API\\ConfigurationController'] = $instance = new \App\API\ConfigurationController(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), ($this->privates['App\\Configuration\\LanguageFormattings'] ?? $this->getLanguageFormattingsService()));

$instance->setContainer(($this->privates['.service_locator.BTdVLEs'] ?? $this->load('get_ServiceLocator_BTdVLEsService.php'))->withContext('App\\API\\ConfigurationController', $this));

return $instance;
