<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Widget\Renderer\CompoundChartRenderer' shared autowired service.

include_once $this->targetDirs[3].'/src/Widget/WidgetRendererInterface.php';
include_once $this->targetDirs[3].'/src/Widget/Renderer/AbstractTwigRenderer.php';
include_once $this->targetDirs[3].'/src/Widget/Renderer/CompoundChartRenderer.php';

return $this->privates['App\\Widget\\Renderer\\CompoundChartRenderer'] = new \App\Widget\Renderer\CompoundChartRenderer(($this->services['twig'] ?? $this->getTwigService()));
