<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Timesheet\Calculator\DurationCalculator' shared autowired service.

include_once $this->targetDirs[3].'/src/Timesheet/CalculatorInterface.php';
include_once $this->targetDirs[3].'/src/Timesheet/Calculator/DurationCalculator.php';

return $this->privates['App\\Timesheet\\Calculator\\DurationCalculator'] = new \App\Timesheet\Calculator\DurationCalculator($this->parameters['kimai.timesheet.rounding']);
