<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Type\DateRangeType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/Type/DateRangeType.php';

return $this->privates['App\\Form\\Type\\DateRangeType'] = new \App\Form\Type\DateRangeType(($this->privates['App\\Utils\\LocaleSettings'] ?? $this->getLocaleSettingsService()), ($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')));
