<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\DashboardSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/DashboardSubscriber.php';

return $this->privates['App\\EventSubscriber\\DashboardSubscriber'] = new \App\EventSubscriber\DashboardSubscriber(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), ($this->privates['App\\Repository\\UserRepository'] ?? $this->getUserRepositoryService()), ($this->privates['App\\Repository\\ActivityRepository'] ?? $this->load('getActivityRepositoryService.php')), ($this->privates['App\\Repository\\ProjectRepository'] ?? $this->load('getProjectRepositoryService.php')), ($this->privates['App\\Repository\\CustomerRepository'] ?? $this->load('getCustomerRepositoryService.php')));
