<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ExportController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/ExportController.php';
include_once $this->targetDirs[3].'/src/Export/ServiceExport.php';

$this->services['App\\Controller\\ExportController'] = $instance = new \App\Controller\ExportController(($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->getTimesheetRepositoryService()), new \App\Export\ServiceExport(new RewindableGenerator(function () {
    yield 0 => ($this->privates['App\\Export\\Renderer\\CsvRenderer'] ?? $this->load('getCsvRendererService.php'));
    yield 1 => ($this->privates['App\\Export\\Renderer\\HtmlRenderer'] ?? $this->load('getHtmlRendererService.php'));
    yield 2 => ($this->privates['App\\Export\\Renderer\\OdsRenderer'] ?? $this->load('getOdsRendererService.php'));
    yield 3 => ($this->privates['App\\Export\\Renderer\\PDFRenderer'] ?? $this->load('getPDFRendererService.php'));
    yield 4 => ($this->privates['App\\Export\\Renderer\\XlsxRenderer'] ?? $this->load('getXlsxRendererService.php'));
}, 5)), ($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')));

$instance->setContainer(($this->privates['.service_locator.OHVJh0X'] ?? $this->load('get_ServiceLocator_OHVJh0XService.php'))->withContext('App\\Controller\\ExportController', $this));

return $instance;
