<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Extension\EnhancedChoiceTypeExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/src/Form/Extension/EnhancedChoiceTypeExtension.php';

return $this->privates['App\\Form\\Extension\\EnhancedChoiceTypeExtension'] = new \App\Form\Extension\EnhancedChoiceTypeExtension(($this->privates['App\\Configuration\\ThemeConfiguration'] ?? $this->getThemeConfigurationService()));
