<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Export\Renderer\HtmlRenderer' shared autowired service.

include_once $this->targetDirs[3].'/src/Export/RendererInterface.php';
include_once $this->targetDirs[3].'/src/Export/Renderer/RendererTrait.php';
include_once $this->targetDirs[3].'/src/Export/Renderer/HtmlRenderer.php';

return $this->privates['App\\Export\\Renderer\\HtmlRenderer'] = new \App\Export\Renderer\HtmlRenderer(($this->services['twig'] ?? $this->getTwigService()));
