<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Command\InstallCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/InstallCommand.php';
include_once $this->targetDirs[3].'/src/Utils/File.php';

$this->privates['App\\Command\\InstallCommand'] = $instance = new \App\Command\InstallCommand($this->targetDirs[3], ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), new \App\Utils\File());

$instance->setName('kimai:install');

return $instance;
