<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.App\Command\KimaiImporterCommand' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/src/Command/KimaiImporterCommand.php';

return $this->services['console.command.public_alias.App\\Command\\KimaiImporterCommand'] = new \App\Command\KimaiImporterCommand(($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php')), ($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->services['validator'] ?? $this->getValidatorService()));
