<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Ldap\LdapUserProvider' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/User/UserProviderInterface.php';
include_once $this->targetDirs[3].'/src/Ldap/LdapUserProvider.php';
include_once $this->targetDirs[3].'/src/Ldap/LdapManager.php';
include_once $this->targetDirs[3].'/src/Ldap/LdapDriver.php';
include_once $this->targetDirs[3].'/src/Configuration/LdapConfiguration.php';
include_once $this->targetDirs[3].'/src/Ldap/LdapUserHydrator.php';

$a = new \App\Configuration\LdapConfiguration($this->parameters['kimai.ldap']);
$b = ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService());

return $this->privates['App\\Ldap\\LdapUserProvider'] = new \App\Ldap\LdapUserProvider(new \App\Ldap\LdapManager(new \App\Ldap\LdapDriver($a, $b), new \App\Ldap\LdapUserHydrator($a, ($this->privates['App\\Security\\RoleService'] ?? $this->load('getRoleServiceService.php'))), $a), $b);
