<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\MenuBuilderSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/MenuBuilderSubscriber.php';

return $this->privates['App\\EventSubscriber\\MenuBuilderSubscriber'] = new \App\EventSubscriber\MenuBuilderSubscriber(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()));
