<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'nelmio_api_doc.describers.config' shared service.

include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/DescriberInterface.php';
include_once $this->targetDirs[3].'/vendor/nelmio/api-doc-bundle/Describer/ExternalDocDescriber.php';

return $this->privates['nelmio_api_doc.describers.config'] = new \Nelmio\ApiDocBundle\Describer\ExternalDocDescriber(['host' => 'localhost', 'basePath' => '', 'schemes' => [0 => 'http'], 'info' => ['title' => 'Kimai 2 - API Docs', 'description' => 'REST API for the Kimai 2 time-tracking software. Read more about its usage in the [API documentation](https://www.kimai.org/documentation/rest-api.html) and then download a [Swagger file](doc.json) for import e.g. in Postman.'."\n".'Be aware: it is not yet considered stable and BC breaks might happen, but we try to avoid them.'."\n".'', 'version' => 0.3], 'securityDefinitions' => ['apiUser' => ['type' => 'apiKey', 'description' => 'Value: {Username}', 'name' => 'X-AUTH-USER', 'in' => 'header'], 'apiToken' => ['type' => 'apiKey', 'description' => 'Value: {API Token}', 'name' => 'X-AUTH-TOKEN', 'in' => 'header']], 'security' => [0 => ['X-AUTH-USER' => []], 1 => ['X-AUTH-TOKEN' => []]]]);
