<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'KevinPapst\AdminLTEBundle\Controller\NavbarController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/vendor/kevinpapst/adminlte-bundle/Controller/EmitterController.php';
include_once $this->targetDirs[3].'/vendor/kevinpapst/adminlte-bundle/Controller/NavbarController.php';

$this->services['KevinPapst\\AdminLTEBundle\\Controller\\NavbarController'] = $instance = new \KevinPapst\AdminLTEBundle\Controller\NavbarController(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['admin_lte_theme.context_helper'] ?? $this->getAdminLteTheme_ContextHelperService()));

$instance->setContainer($this);

return $instance;
