<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Export\Renderer\OdsRenderer' shared autowired service.

include_once $this->targetDirs[3].'/src/Export/Renderer/AbstractSpreadsheetRenderer.php';
include_once $this->targetDirs[3].'/src/Export/RendererInterface.php';
include_once $this->targetDirs[3].'/src/Export/Renderer/OdsRenderer.php';

return $this->privates['App\\Export\\Renderer\\OdsRenderer'] = new \App\Export\Renderer\OdsRenderer(($this->services['translator'] ?? $this->getTranslatorService()), ($this->privates['App\\Twig\\DateExtensions'] ?? $this->getDateExtensionsService()), ($this->privates['App\\Twig\\Extensions'] ?? $this->getExtensionsService()));
