<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Voter\ProjectVoter' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/VoterInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Core/Authorization/Voter/Voter.php';
include_once $this->targetDirs[3].'/src/Voter/AbstractVoter.php';
include_once $this->targetDirs[3].'/src/Voter/ProjectVoter.php';

return $this->privates['App\\Voter\\ProjectVoter'] = new \App\Voter\ProjectVoter(($this->privates['App\\Security\\AclDecisionManager'] ?? $this->load('getAclDecisionManagerService.php')), ($this->privates['App\\Security\\RolePermissionManager'] ?? $this->load('getRolePermissionManagerService.php')));
