<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Export\Renderer\PDFRenderer' shared autowired service.

include_once $this->targetDirs[3].'/src/Export/RendererInterface.php';
include_once $this->targetDirs[3].'/src/Export/Renderer/RendererTrait.php';
include_once $this->targetDirs[3].'/src/Export/Renderer/PDFRenderer.php';
include_once $this->targetDirs[3].'/src/Utils/HtmlToPdfConverter.php';
include_once $this->targetDirs[3].'/src/Utils/MPdfConverter.php';

return $this->privates['App\\Export\\Renderer\\PDFRenderer'] = new \App\Export\Renderer\PDFRenderer(($this->services['twig'] ?? $this->getTwigService()), ($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')), new \App\Utils\MPdfConverter($this->targetDirs[0]));
