<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.8SSwaBs.App\Entity\Project' shared service.

include_once $this->targetDirs[3].'/src/Entity/EntityWithMetaFields.php';
include_once $this->targetDirs[3].'/src/Entity/RatesTrait.php';
include_once $this->targetDirs[3].'/src/Entity/ColorTrait.php';
include_once $this->targetDirs[3].'/src/Entity/BudgetTrait.php';
include_once $this->targetDirs[3].'/src/Entity/Project.php';

return $this->privates['.errored..service_locator.8SSwaBs.App\\Entity\\Project'] = new \App\Entity\Project();
