<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Security\RoleService' shared autowired service.

include_once $this->targetDirs[3].'/src/Security/RoleService.php';

return $this->privates['App\\Security\\RoleService'] = new \App\Security\RoleService($this->parameters['security.role_hierarchy.roles']);
