<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Widget\Renderer\SimpleWidgetRenderer' shared autowired service.

include_once $this->targetDirs[3].'/src/Widget/WidgetRendererInterface.php';
include_once $this->targetDirs[3].'/src/Widget/Renderer/AbstractTwigRenderer.php';
include_once $this->targetDirs[3].'/src/Widget/Renderer/SimpleWidgetRenderer.php';

return $this->privates['App\\Widget\\Renderer\\SimpleWidgetRenderer'] = new \App\Widget\Renderer\SimpleWidgetRenderer(($this->services['twig'] ?? $this->getTwigService()));
