<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'KevinPapst\AdminLTEBundle\Controller\SidebarController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/vendor/kevinpapst/adminlte-bundle/Controller/EmitterController.php';
include_once $this->targetDirs[3].'/vendor/kevinpapst/adminlte-bundle/Controller/SidebarController.php';

$this->services['KevinPapst\\AdminLTEBundle\\Controller\\SidebarController'] = $instance = new \KevinPapst\AdminLTEBundle\Controller\SidebarController(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setContainer($this);

return $instance;
