<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Doctrine\SqliteSessionInitSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/Doctrine/SqliteSessionInitSubscriber.php';

return $this->privates['App\\Doctrine\\SqliteSessionInitSubscriber'] = new \App\Doctrine\SqliteSessionInitSubscriber();
