<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Extension\SelectWithApiDataExtension' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeExtensionInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractTypeExtension.php';
include_once $this->targetDirs[3].'/src/Form/Extension/SelectWithApiDataExtension.php';

return $this->privates['App\\Form\\Extension\\SelectWithApiDataExtension'] = new \App\Form\Extension\SelectWithApiDataExtension(($this->services['router'] ?? $this->getRouterService()));
