<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Invoice\ServiceInvoice' shared autowired service.

include_once $this->targetDirs[3].'/src/Invoice/ServiceInvoice.php';
include_once $this->targetDirs[3].'/src/Repository/InvoiceDocumentRepository.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/RendererTrait.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/AbstractRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/AbstractSpreadsheetRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/RendererInterface.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/CsvRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/DocxRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/OdsRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/TwigRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/Renderer/XlsxRenderer.php';
include_once $this->targetDirs[3].'/src/Invoice/NumberGeneratorInterface.php';
include_once $this->targetDirs[3].'/src/Invoice/NumberGenerator/DateNumberGenerator.php';
include_once $this->targetDirs[3].'/src/Invoice/Calculator/AbstractCalculator.php';
include_once $this->targetDirs[3].'/src/Invoice/Calculator/AbstractMergedCalculator.php';
include_once $this->targetDirs[3].'/src/Invoice/CalculatorInterface.php';
include_once $this->targetDirs[3].'/src/Invoice/Calculator/ActivityInvoiceCalculator.php';
include_once $this->targetDirs[3].'/src/Invoice/Calculator/DefaultCalculator.php';
include_once $this->targetDirs[3].'/src/Invoice/Calculator/ShortInvoiceCalculator.php';
include_once $this->targetDirs[3].'/src/Invoice/Calculator/UserInvoiceCalculator.php';

$this->privates['App\\Invoice\\ServiceInvoice'] = $instance = new \App\Invoice\ServiceInvoice(new \App\Repository\InvoiceDocumentRepository($this->parameters['kimai.invoice.documents']));

$a = ($this->services['translator'] ?? $this->getTranslatorService());
$b = ($this->privates['App\\Twig\\DateExtensions'] ?? $this->getDateExtensionsService());
$c = ($this->privates['App\\Twig\\Extensions'] ?? $this->getExtensionsService());

$instance->addRenderer(new \App\Invoice\Renderer\CsvRenderer($a, $b, $c));
$instance->addRenderer(new \App\Invoice\Renderer\DocxRenderer($a, $b, $c));
$instance->addRenderer(new \App\Invoice\Renderer\OdsRenderer($a, $b, $c));
$instance->addRenderer(new \App\Invoice\Renderer\TwigRenderer(($this->services['twig'] ?? $this->getTwigService())));
$instance->addRenderer(new \App\Invoice\Renderer\XlsxRenderer($a, $b, $c));
$instance->addNumberGenerator(new \App\Invoice\NumberGenerator\DateNumberGenerator());
$instance->addCalculator(new \App\Invoice\Calculator\ActivityInvoiceCalculator());
$instance->addCalculator(new \App\Invoice\Calculator\DefaultCalculator());
$instance->addCalculator(new \App\Invoice\Calculator\ShortInvoiceCalculator());
$instance->addCalculator(new \App\Invoice\Calculator\UserInvoiceCalculator());

return $instance;
