<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\StatusController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/API/BaseApiController.php';
include_once $this->targetDirs[3].'/src/API/StatusController.php';

$this->services['App\\API\\StatusController'] = $instance = new \App\API\StatusController(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')));

$instance->setContainer(($this->privates['.service_locator.BTdVLEs'] ?? $this->load('get_ServiceLocator_BTdVLEsService.php'))->withContext('App\\API\\StatusController', $this));

return $instance;
