<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Validator\Constraints\TimesheetValidator' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/validator/ConstraintValidator.php';
include_once $this->targetDirs[3].'/src/Validator/Constraints/TimesheetValidator.php';

return $this->privates['App\\Validator\\Constraints\\TimesheetValidator'] = new \App\Validator\Constraints\TimesheetValidator(($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), ($this->privates['App\\Configuration\\TimesheetConfiguration'] ?? $this->getTimesheetConfigurationService()), ($this->privates['App\\Timesheet\\TrackingModeService'] ?? $this->load('getTrackingModeServiceService.php')));
