<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\API\TimesheetController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/API/BaseApiController.php';
include_once $this->targetDirs[3].'/src/API/TimesheetController.php';

$this->services['App\\API\\TimesheetController'] = $instance = new \App\API\TimesheetController(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), ($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->getTimesheetRepositoryService()), ($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')), ($this->privates['App\\Configuration\\TimesheetConfiguration'] ?? $this->getTimesheetConfigurationService()), ($this->privates['App\\Repository\\TagRepository'] ?? $this->load('getTagRepositoryService.php')), ($this->privates['App\\Timesheet\\TrackingModeService'] ?? $this->load('getTrackingModeServiceService.php')));

$instance->setContainer(($this->privates['.service_locator.BTdVLEs'] ?? $this->load('get_ServiceLocator_BTdVLEsService.php'))->withContext('App\\API\\TimesheetController', $this));

return $instance;
