<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\TimesheetController' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[3].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/AbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/TimesheetAbstractController.php';
include_once $this->targetDirs[3].'/src/Controller/TimesheetController.php';

$this->services['App\\Controller\\TimesheetController'] = $instance = new \App\Controller\TimesheetController(($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')), ($this->privates['App\\Configuration\\TimesheetConfiguration'] ?? $this->getTimesheetConfigurationService()), ($this->privates['App\\Repository\\TimesheetRepository'] ?? $this->getTimesheetRepositoryService()), ($this->privates['App\\Timesheet\\TrackingModeService'] ?? $this->load('getTrackingModeServiceService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setContainer(($this->privates['.service_locator.OHVJh0X'] ?? $this->load('get_ServiceLocator_OHVJh0XService.php'))->withContext('App\\Controller\\TimesheetController', $this));

return $instance;
