<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\TimesheetAdminEditForm' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/TimesheetEditForm.php';
include_once $this->targetDirs[3].'/src/Form/TimesheetAdminEditForm.php';

return $this->privates['App\\Form\\TimesheetAdminEditForm'] = new \App\Form\TimesheetAdminEditForm(($this->privates['App\\Repository\\CustomerRepository'] ?? $this->load('getCustomerRepositoryService.php')), ($this->privates['App\\Repository\\ProjectRepository'] ?? $this->load('getProjectRepositoryService.php')), ($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')));
