<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Type\TrackingModeType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/Type/TrackingModeType.php';

return $this->privates['App\\Form\\Type\\TrackingModeType'] = new \App\Form\Type\TrackingModeType(($this->privates['App\\Timesheet\\TrackingModeService'] ?? $this->load('getTrackingModeServiceService.php')));
