<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Timesheet\TrackingModeService' shared autowired service.

include_once $this->targetDirs[3].'/src/Timesheet/TrackingModeService.php';

return $this->privates['App\\Timesheet\\TrackingModeService'] = new \App\Timesheet\TrackingModeService(($this->privates['App\\Timesheet\\UserDateTimeFactory'] ?? $this->load('getUserDateTimeFactoryService.php')), ($this->privates['App\\Configuration\\TimesheetConfiguration'] ?? $this->getTimesheetConfigurationService()));
