<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Form\Type\UserRoleType' shared autowired service.

include_once $this->targetDirs[3].'/vendor/symfony/form/FormTypeInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/form/AbstractType.php';
include_once $this->targetDirs[3].'/src/Form/Type/UserRoleType.php';

return $this->privates['App\\Form\\Type\\UserRoleType'] = new \App\Form\Type\UserRoleType(($this->privates['App\\Security\\RoleService'] ?? $this->load('getRoleServiceService.php')));
