<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\EventSubscriber\UserPreferenceSubscriber' shared autowired service.

include_once $this->targetDirs[3].'/src/EventSubscriber/UserPreferenceSubscriber.php';

return $this->privates['App\\EventSubscriber\\UserPreferenceSubscriber'] = new \App\EventSubscriber\UserPreferenceSubscriber(($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->services['security.authorization_checker'] ?? $this->getSecurity_AuthorizationCheckerService()), ($this->privates['App\\Configuration\\FormConfiguration'] ?? $this->load('getFormConfigurationService.php')));
