<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InvoiceTemplate extends \App\Entity\InvoiceTemplate implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'id', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'name', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'title', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'company', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'address', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'dueDays', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'vat', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'calculator', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'numberGenerator', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'renderer', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'paymentTerms'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'id', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'name', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'title', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'company', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'address', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'dueDays', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'vat', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'calculator', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'numberGenerator', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'renderer', '' . "\0" . 'App\\Entity\\InvoiceTemplate' . "\0" . 'paymentTerms'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InvoiceTemplate $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(?string $address): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$address]);

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumberGenerator(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumberGenerator', []);

        return parent::getNumberGenerator();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumberGenerator(string $numberGenerator): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumberGenerator', [$numberGenerator]);

        return parent::setNumberGenerator($numberGenerator);
    }

    /**
     * {@inheritDoc}
     */
    public function getDueDays(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDueDays', []);

        return parent::getDueDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setDueDays(int $dueDays): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDueDays', [$dueDays]);

        return parent::setDueDays($dueDays);
    }

    /**
     * {@inheritDoc}
     */
    public function getVat(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVat', []);

        return parent::getVat();
    }

    /**
     * {@inheritDoc}
     */
    public function setVat(float $vat): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVat', [$vat]);

        return parent::setVat($vat);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', []);

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany(string $company): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', [$company]);

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getRenderer(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRenderer', []);

        return parent::getRenderer();
    }

    /**
     * {@inheritDoc}
     */
    public function setRenderer(string $renderer): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRenderer', [$renderer]);

        return parent::setRenderer($renderer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCalculator(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalculator', []);

        return parent::getCalculator();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalculator(string $calculator): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalculator', [$calculator]);

        return parent::setCalculator($calculator);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentTerms(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentTerms', []);

        return parent::getPaymentTerms();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentTerms(?string $paymentTerms): \App\Entity\InvoiceTemplate
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentTerms', [$paymentTerms]);

        return parent::setPaymentTerms($paymentTerms);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
